- Target: nmaguiar/gcutils:build (alpine 3.22.0)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: Node.js
  Class: lang-pkgs
  Type: node-pkg
- Target: Python
  Class: lang-pkgs
  Type: python-pkg
- Target: usr/bin/prometheus
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/promtool
  Class: lang-pkgs
  Type: gobinary
- Target: usr/share/grafana/bin/grafana
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-48371
    PkgID: github.com/openfga/openfga@v1.8.12
    PkgName: github.com/openfga/openfga
    PkgIdentifier:
      PURL: pkg:golang/github.com/openfga/openfga@v1.8.12
      UID: 3d13096c276c89b0
    InstalledVersion: v1.8.12
    FixedVersion: 1.8.13
    Status: fixed
    Layer:
      Digest: sha256:d253c11497bdc7c88bcb2fd17d32c6e18cbe53cf7cb69f23a5d7c92ceb2f8ed5
      DiffID: sha256:a5692e237fc0a903f126ab825a18b72e43934098e974496e054bc4bf9b9bd481
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-48371
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: OpenFGA Authorization Bypass
    Description: 'OpenFGA is an authorization/permission engine. OpenFGA versions 1.8.0 through 1.8.12 (corresponding to Helm chart openfga-0.2.16 through openfga-0.2.30 and docker 1.8.0 through 1.8.12) are vulnerable to authorization bypass when certain Check and ListObject calls are executed. Users are affected under four specific conditions: First, calling Check API or ListObjects with an authorization model that has a relationship directly assignable by both type bound public access and userset; second, there are check or list object queries with contextual tuples for the relationship that can be directly assignable by both type bound public access and userset; third, those contextual tuples’s user field is an userset; and finally, type bound public access tuples are not assigned to the relationship. Users should upgrade to version 1.8.13 to receive a patch. The upgrade is backwards compatible.'
    Severity: MEDIUM
    CweIDs:
    - CWE-285
    VendorSeverity:
      ghsa: 2
    References:
    - https://github.com/openfga/openfga
    - https://github.com/openfga/openfga/commit/e5960d4eba92b723de8ff3a5346a07f50c1379ca
    - https://github.com/openfga/openfga/security/advisories/GHSA-c72g-53hw-82q7
    - https://nvd.nist.gov/vuln/detail/CVE-2025-48371
    - https://pkg.go.dev/vuln/GO-2025-3707
    PublishedDate: '2025-05-22T23:15:19.23Z'
    LastModifiedDate: '2025-05-23T15:54:42.643Z'
- Target: usr/share/grafana/bin/grafana-cli
  Class: lang-pkgs
  Type: gobinary
- Target: usr/share/grafana/bin/grafana-server
  Class: lang-pkgs
  Type: gobinary
